### <font color='black'>Curso Big Data Real-Time Analytics com Python e Spark</font>

### <font color='black'>Limpeza e Pré-Processamento de Dados com NumPy</font>

   O conjunto de dados representa milhares de empréstimos feitos por meio da plataforma Lending club, que permite que indivíduos emprestem para outros indivíduos. O conjunto de dados representa apenas emprestimos efetivamente feitos e o dataset está disponível no link: https://www.openintro.org/data/index.php?data=loans_full_schema (dataset1)
  

No dataset2 temos ma cotação do dólar em relação ao Euro, que pode ser visto no link: https://finance.yahoo.com/

 O presente treinamento tem como objetivo a limpeza e o preprocessamento dos datasets utilizando o Numpy.

In [1]:
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

### Carregando o dataset

In [3]:
#Define formatação de impressão do Numpy
np.set_printoptions(suppress=True, linewidth=200, precision=2)

In [4]:
#Importando os dados no dataset1
data1 = np.genfromtxt('dados\dataset1.csv', 
                      delimiter=';', 
                      skip_header = 1, 
                      autostrip = True, 
                      encoding = 'cp1252')

In [5]:
#Numpy não identificou algumas variáveis no tipo string, identificando como nan
data1.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [6]:
#Verificando o tamanho do dataset
data1.shape

(10000, 14)

In [7]:
data1.dtype

dtype('float64')

__Verificando valores ausentes__

In [8]:
np.isnan(data1).sum()

88005

In [9]:
valor_max = np.nanmax(data1) + 1
print(valor_max)

68616520.0


In [10]:
#calculando a média sem nan
media_nan = np.nanmean(data1, axis=0)
print(media_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [11]:
#Verificando quais são as colunas do tipo string dentro do array de dados

colunas_string = np.argwhere(np.isnan(media_nan)).squeeze()
colunas_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
colunas_numericas = np.argwhere(np.isnan(media_nan) == False).squeeze()
colunas_numericas

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [13]:
#Identificadas as colunas string e numéricas, vamos carregar novamente os dados para identificar a variáveis string

data_string = np.genfromtxt('dados\dataset1.csv', 
                      delimiter=';', 
                      skip_header = 1, 
                      autostrip = True, 
                      usecols=colunas_string,
                      dtype=str,
                      encoding = 'cp1252')
data_string.view()

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [14]:
data_numeric = np.genfromtxt('dados\dataset1.csv', 
                      delimiter=';', 
                      skip_header = 1, 
                      autostrip = True, 
                      usecols=colunas_numericas,
                      filling_values=valor_max,
                      encoding = 'cp1252')
data_numeric.view()

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [15]:
#Buscando os nomes das colunas

colunms_names = np.genfromtxt('dados\dataset1.csv', 
                               delimiter=';', 
                               autostrip = True, 
                               skip_footer=data1.shape[0],
                               dtype=str,
                               encoding = 'cp1252')
colunms_names

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [16]:
header_string, header_numeric = colunms_names[colunas_string], colunms_names[colunas_numericas]
print(header_string)
print(header_numeric)

['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']
['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


__Salvando as alterações__

In [17]:
def checkpoint(file_name, arr_header, arr_data):
    np.savez(file_name, header=arr_header, data=arr_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [18]:
first_checkpoint = checkpoint('dados/checkpoint_inicial', header_string, data_string)

In [19]:
first_checkpoint['data']

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [20]:
np.array_equal(first_checkpoint['data'], data_string)

True


__Manipulando coluna Issue_date__

In [21]:
#Nomes das colunas com dados strings
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [22]:
header_string[0] = 'issue_date'

In [23]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [24]:
#Dados da coluna issue_date
np.unique(data_string[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
#Removendo o final -15
data_string[:, 0] = np.chararray.strip(data_string[:, 0], '-15')
np.unique(data_string[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [26]:
meses = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [27]:
#Converter os nomes dos meses em valores numéricos

for i in range(13):
    data_string[:, 0] = np.where(data_string[:, 0] == meses[i], i, data_string[:, 0])

In [28]:
#O valor zero siginifica valor ausente
np.unique(data_string[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

__Manipulando coluna loan_status__

In [29]:
print("Quais são as variáveis loan_status", np.unique(data_string[:, 1]))
print("Número de variáveis", np.unique(data_string[:, 1]).size)

Quais são as variáveis loan_status ['' 'Charged Off' 'Current' 'Default' 'Fully Paid' 'In Grace Period' 'Issued' 'Late (16-30 days)' 'Late (31-120 days)']
Número de variáveis 9


In [30]:
#Escolhendo as 3 categoricas problemáticas

status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [31]:
data_string[:, 1] = np.where(np.isin(data_string[:, 1], status_bad), 0, 1)

In [32]:
np.unique(data_string[:, 1])

array(['0', '1'], dtype='<U69')

In [33]:
data_string.view()

array([['5', '1', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

__Manipulando coluna Term__

In [34]:
print("Quais são as variáveis term", np.unique(data_string[:, 2]))
print("Número de variáveis", np.unique(data_string[:, 2]).size)

Quais são as variáveis term ['' '36 months' '60 months']
Número de variáveis 3


In [35]:
#Removendo o final months
data_string[:, 2] = np.chararray.strip(data_string[:, 2], ' months')
np.unique(data_string[:, 2])

array(['', '36', '60'], dtype='<U69')

In [36]:
#Renomeando a variável
header_string[2] = 'term_months'

In [37]:
#Substituindo valores ausentes pelo valor maior
data_string[:,2] = np.where(data_string[:,2] == '', '60', data_string[:,2])

In [38]:
np.unique(data_string[:,2])

array(['36', '60'], dtype='<U69')

__Manipulando coluna Grade e SubGrade__

In [39]:
#Verificando os dados das variáveis
np.unique(data_string[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [40]:
np.unique(data_string[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [41]:
np.unique(data_string[:, 3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [42]:
#ajuste da variavel subgrade
for i in np.unique(data_string[:, 3])[1:]:
    data_string[:, 4] = np.where((data_string[:, 4] == '') & (data_string[:, 3] == i), i + '5', data_string[:,4])

In [43]:
np.unique(data_string[:, 4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [44]:
#Substituindo valores ausentes por uma nova categoria
data_string[:, 4] = np.where(data_string[:, 4] == '', 'H1', data_string[:, 4])

In [45]:
np.unique(data_string[:, 4], return_counts=True )

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
        'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9], dtype=int64))

In [46]:
#Removendo variavel Grade e mantendo a subgrade

data_string = np.delete(data_string, 3, axis=1)

In [47]:
#Agora o indice 3 é a variavel subgrade
data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [48]:
header_string = np.delete(header_string, 3)

In [49]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [50]:
#Convertendo a variavel pela representação numérica
np.unique(data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [51]:
#Criando uma lista de chaves

keys = list(np.unique(data_string[:,3]))

In [52]:
keys[0]

'A1'

In [53]:
#Cris uma lista de valores adicionando um numero para cada subgrade

values = list(range(1, np.unique(data_string[:,3]).shape[0] + 1))

In [54]:
values[0:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [55]:
#Criando dicionario

dict_sub_grade = dict(zip(keys, values))

In [56]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [57]:
#Substituindo a string pela representação numerica

for i in np.unique(data_string[:,3]):
    data_string[:,3] = np.where(data_string[:,3] == i, dict_sub_grade[i], data_string[:,3])

In [58]:
np.unique(data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

__Manipulando variável Status__

In [59]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [60]:
np.unique(data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [61]:
#Binarização da variavel status

data_string[:,4] = np.where((data_string[:,4] == 'Not Verified') | (data_string[:,4] == ''), 0, 1)

In [62]:
np.unique(data_string[:,4])

array(['0', '1'], dtype='<U69')

__Manipulando variável url com extração de ID__

In [63]:
data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [64]:
#Removendo a url e mantendo o ID
data_string[:,5] = np.chararray.strip(data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')    

In [65]:
data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [66]:
#Converter para int
data_string[:,5].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [67]:
#A primeira coluna do array numerico tb possui os Ids com tipo float
data_numeric[:,0].dtype

dtype('float64')

In [68]:
#Atualizando os tipos dos Ids do array numerico
data_numeric[:,0].astype(dtype=np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [69]:
#comparando as 2 colunas para verificar se é a mesma informação
np.array_equal(data_string[:,5].astype(dtype=np.int32), data_numeric[:,0].astype(dtype=np.int32))

True

In [70]:
#como existe a mesma informação, uma das colunas pode ser deletada
data_string = np.delete(data_string, 5, axis=1)

In [71]:
#Removendo do header
header_string = np.delete(header_string, 5)

In [72]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

__Manipulando a ultima variável addr_state__

In [73]:
#Verificando os dados
states_names, states_count = np.unique(data_string[:, 5], return_counts=True)

In [74]:
states_count

array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,   84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,  341,   57,
        130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,   17,  216,  148,   49,   27], dtype=int64)

In [75]:
#Ordenando 
states_count_sorted = np.argsort(-states_count)

In [76]:
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64))

In [77]:
#Substituindo valor ausente por  0
data_string[:,5] = np.where(data_string[:,5] == '', 0, data_string[:,5]) 

In [78]:
np.unique(data_string[:,5]) 

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [79]:
#Separando Estados por Região
#Referencia:https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [80]:
#Categorizando os Estados
data_string[:,5] = np.where(np.isin(data_string[:,5], states_west), 1, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5], states_south), 2, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5], states_midwest), 3, data_string[:,5])
data_string[:,5] = np.where(np.isin(data_string[:,5], states_east), 4, data_string[:,5])

In [81]:
np.unique(data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [82]:
#Convertendo array de string para int
data_string = data_string.astype(int)

In [83]:
data_string.dtype

dtype('int32')

In [84]:
#Salvando
checkpoint_string = checkpoint('dados/checkpoint-string', header_string, data_string)

In [85]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

__Manipulação das Variáveis Numéricas__

In [86]:
data_numeric.view()

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [87]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [88]:
data_numeric.dtype

dtype('float64')

In [89]:
#Verificando se existem valores nan
np.isnan(data_numeric).sum()

0

In [90]:
#Criando um array de minimos, média e maximos para tratar os valores ausentes

arr_stats = np.array([np.nanmin(data1, axis=0), media_nan, np.nanmax(data1, axis=0)])

print(arr_stats[0])

[373332.         nan   1000.         nan   1000.         nan      6.       31.42       nan       nan       nan       nan       nan      0.  ]


In [91]:
arr_stats[:, colunas_numericas]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

__Processando a Variavel funded_amount__

In [92]:
data_numeric[:, 2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [93]:
arr_stats[0, colunas_numericas[2]]

1000.0

In [94]:
#Substituindo valores ausentes pelo valor minimo

data_numeric[:,2] = np.where(data_numeric[:,2] == valor_max, arr_stats[0, colunas_numericas[2]], data_numeric[:,2])

In [95]:
data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

__Processando as demais variáveis__


In [96]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [97]:
# Substituindo o valor ausente (valor_max) pelos valores do array de estatísticas
for i in [1,3,4,5]:
    data_numeric[:,i] = np.where(data_numeric[:,i] == valor_max, 
                                arr_stats[2, colunas_numericas[i]], 
                                data_numeric[:,i])

In [98]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Carregando o dataset 2 de cotações

In [99]:
#Importando os dados no dataset2
data_cotacao = np.genfromtxt('dados\dataset2.csv', 
                      delimiter=',', 
                      skip_header = 1, 
                      usecols=3,
                      autostrip = True)

In [100]:
data_cotacao.shape

(12,)

In [101]:
#A primera coluna são os meses do lançamento
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [102]:
data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [103]:
exchange_rate  = data_string[:,0]

In [104]:
exchange_rate

array([ 5,  0,  9, ...,  6,  4, 12])

In [105]:
#Preencher a variavel exchange_rate com a taxa correspondente ao mes
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, data_cotacao[i - 1], exchange_rate)

In [106]:
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [107]:
#Substituindo os ausentes pela media
exchange_rate = np.where(exchange_rate == 0, np.mean(data_cotacao), exchange_rate)

In [108]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [109]:
#executando o reshape
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [110]:
#Concatenando os arrays
data_numeric = np.hstack((data_numeric, exchange_rate))

In [111]:
# Inclui o nome da coluna no array de nomes de colunas
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))

In [112]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

Criando colunas para taxa de cambio em Dolar e Euro

In [113]:
#Array com os indices que usam dolar
colunms_dollar = np.array([1,2,4,5])

In [114]:
data_numeric.shape

(10000, 7)

In [115]:
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in colunms_dollar:
    data_numeric = np.hstack((data_numeric, np.reshape(data_numeric[:,i] / data_numeric[:,6], (10000,1))))

In [116]:
data_numeric.shape

(10000, 11)

In [117]:
data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [118]:
#Ajustabdo os nomes das colunas
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[colunms_dollar]])

In [119]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [120]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [121]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [122]:
header_numeric[colunms_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[colunms_dollar]])

In [123]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [124]:
#Ordenando
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [125]:
header_numeric = header_numeric[columns_index_order]

In [126]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [127]:
#Ordenando array numerico 
data_numeric = data_numeric[:,columns_index_order]

In [128]:
data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

__Variavel int_rate__

In [129]:
#Apresentar em porcentagem
data_numeric[:,5] = data_numeric[:,5]/100

In [130]:
data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Ultimo checkpoint com Variáveis Numéricas

In [131]:
checkpoint_numeric = checkpoint("dados/checkpoint_numeric", header_numeric, data_numeric)

In [132]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

### Gerando o dataset final

In [133]:
checkpoint_string['data'].shape

(10000, 6)

In [134]:
checkpoint_numeric['data'].shape

(10000, 11)

In [135]:
# Concatena os arrays
dataset_final = np.hstack((checkpoint_numeric['data'], checkpoint_string['data']))

In [137]:
dataset_final.shape

(10000, 17)

In [138]:
# Concatena os arrays de nomes de colunas
header_final = np.concatenate((checkpoint_numeric['header'], checkpoint_string['header']))

In [146]:
header_final

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [141]:
# Ordenando o dataset
dataset_final = dataset_final[np.argsort(dataset_final[:,0])]

In [142]:
dataset_final

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

### Gravando o dataset final pré processado

In [143]:
#Concatenando header com array de dados

df_final = np.vstack((header_final, dataset_final))

In [144]:
np.savetxt('dados/dataset_final.csv', 
           df_final, 
           fmt='%s', 
           delimiter=',')

In [145]:
df_final.view()

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status', 'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')